-- ============================================================================
-- Museum Pipeline — optional Emotion module
--
-- Generic persistence for controlled-vocabulary emotion/resonance readings.
-- Vocabulary concepts, concept networks and museum-specific editorial resources
-- belong to the museum profile and are NOT defined here.
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS museum;


CREATE TABLE IF NOT EXISTS museum.emotion_assignments (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    obj_id              text        NOT NULL,
    annotation_set_id   text        NOT NULL,
    concept_id          text        NOT NULL,

    preferred_label     text,
    reading_mode        text,
    concept_role        text,
    semantic_domains    text[]      NOT NULL DEFAULT '{}',

    reading_statement   text        NOT NULL,
    reading_scope       text        NOT NULL DEFAULT 'object_overall',
    why                 text,
    evidence            jsonb       NOT NULL DEFAULT '[]',

    judge_status        text        NOT NULL DEFAULT 'ungeprueft',
    judge_action        text,
    judge_comment       text,
    concept_id_original text,
    validation_issues   text[]      NOT NULL DEFAULT '{}',

    perspective_type    text        NOT NULL,
    vocabulary_version  text        NOT NULL,

    generator_model     text,
    judge_model         text,
    generator_prompt    text,
    judge_prompt        text,
    caption_used        text,

    created_at          timestamptz NOT NULL DEFAULT now(),

    UNIQUE (annotation_set_id, obj_id, concept_id, reading_scope)
);

CREATE INDEX IF NOT EXISTS emotion_assignments_obj_idx
    ON museum.emotion_assignments (obj_id);

CREATE INDEX IF NOT EXISTS emotion_assignments_concept_idx
    ON museum.emotion_assignments (concept_id);

CREATE INDEX IF NOT EXISTS emotion_assignments_status_idx
    ON museum.emotion_assignments (judge_status);

CREATE INDEX IF NOT EXISTS emotion_assignments_domains_idx
    ON museum.emotion_assignments USING gin (semantic_domains);


CREATE TABLE IF NOT EXISTS museum.emotion_runs (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    obj_id                text        NOT NULL,
    annotation_set_id     text        NOT NULL,

    reading_count         integer     NOT NULL DEFAULT 0,
    visible_findings      text[]      NOT NULL DEFAULT '{}',
    depicted_situations   text[]      NOT NULL DEFAULT '{}',
    free_effects          jsonb       NOT NULL DEFAULT '[]',
    unmappable_effects    jsonb       NOT NULL DEFAULT '[]',
    considered_rejected   jsonb       NOT NULL DEFAULT '[]',
    no_reading_reason     text,

    caption_used          text,
    vocabulary_version    text        NOT NULL,
    generator_model       text,
    judge_model           text,
    generator_prompt      text,

    created_at            timestamptz NOT NULL DEFAULT now(),

    UNIQUE (annotation_set_id, obj_id)
);

CREATE INDEX IF NOT EXISTS emotion_runs_obj_idx
    ON museum.emotion_runs (obj_id);

CREATE INDEX IF NOT EXISTS emotion_runs_count_idx
    ON museum.emotion_runs (reading_count);

CREATE INDEX IF NOT EXISTS emotion_runs_unmappable_idx
    ON museum.emotion_runs USING gin (unmappable_effects);
