-- ============================================================================
-- Museum Pipeline — optional Topics module
--
-- Generic persistence for topic assignments and topic runs.
-- Museum-specific taxonomies, vocabularies, frameworks and resource queries
-- belong to the museum profile and are NOT defined here.
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS museum;


CREATE TABLE IF NOT EXISTS museum.topic_assignments (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    obj_id            text        NOT NULL,
    topic             text        NOT NULL,
    slug              text        NOT NULL,
    source            text        NOT NULL DEFAULT 'llm',
    status            text,
    relation_types    text[],
    rationale         text,
    judge_status      text,
    judge_decision    text,
    review_class      text,
    mandatory_review  boolean,
    detail            jsonb,
    taxonomy_version  text        NOT NULL,
    annotation_set    text,
    updated_at        timestamptz NOT NULL DEFAULT now(),

    UNIQUE (obj_id, topic, source)
);

CREATE INDEX IF NOT EXISTS topic_assignments_obj_idx
    ON museum.topic_assignments (obj_id);

CREATE INDEX IF NOT EXISTS topic_assignments_topic_idx
    ON museum.topic_assignments (topic);

CREATE INDEX IF NOT EXISTS topic_assignments_judge_status_idx
    ON museum.topic_assignments (judge_status);


CREATE TABLE IF NOT EXISTS museum.topic_runs (
    obj_id             text        NOT NULL,
    annotation_set_id  text        NOT NULL,
    object_findings    jsonb,
    taxonomy_version   text,
    generator_model    text        NOT NULL,
    judge_model        text        NOT NULL,
    assignment_count   integer     NOT NULL DEFAULT 0,
    created_at         timestamptz NOT NULL DEFAULT now(),

    PRIMARY KEY (annotation_set_id, obj_id)
);

CREATE INDEX IF NOT EXISTS topic_runs_obj_idx
    ON museum.topic_runs (obj_id);
