-- ============================================================================
-- Museum Pipeline — generic core database schema
--
-- Contains only pipeline-owned output tables required by the core workflow.
--
-- Intentionally NOT included:
--   * institution source/raw tables
--   * Emotion vocabularies and result tables
--   * Topics taxonomies and result tables
--   * GND/OpenSearch data
--   * provider/deployment-specific ownership
--   * runtime resume tables (created by RunState)
--
-- The internal pipeline namespace is intentionally fixed as `museum`.
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS museum;


-- ---------------------------------------------------------------------------
-- Image and text embeddings
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS museum.embeddings (
    obj_id       text        NOT NULL,
    kind         text        NOT NULL,
    modell       text        NOT NULL,
    dim          integer     NOT NULL,
    vec          jsonb       NOT NULL,
    erstellt_am  timestamptz NOT NULL DEFAULT now(),
    sparse       jsonb,

    PRIMARY KEY (obj_id, kind, modell),

    CONSTRAINT embeddings_dim_positive
        CHECK (dim > 0)
);

CREATE INDEX IF NOT EXISTS emb_kind_idx
    ON museum.embeddings (kind, modell);


-- ---------------------------------------------------------------------------
-- Captions / consolidated visual findings
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS museum.enrichment_captions (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    obj_id             text        NOT NULL,
    caption            text,
    modell             text        NOT NULL,
    version            text,
    sprache            text        DEFAULT 'de',
    status             text        NOT NULL DEFAULT 'vorschlag',
    erstellt_am        timestamptz NOT NULL DEFAULT now(),

    master_caption     text,
    res_qwen           text,
    res_gemma          text,
    text_visuell       text,
    text_kontext       text,
    transkription      text,
    hat_transkription  boolean,
    sensitiv_flag      boolean,
    parse_ok           boolean,
    tokens_total       integer,

    UNIQUE (obj_id, modell)
);

CREATE INDEX IF NOT EXISTS enr_cap_mod_idx
    ON museum.enrichment_captions (modell);

CREATE INDEX IF NOT EXISTS enr_cap_obj_idx
    ON museum.enrichment_captions (obj_id);


-- ---------------------------------------------------------------------------
-- Deterministic image-derived features
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS museum.enrichment_derived (
    obj_id              text        PRIMARY KEY,
    format              text,
    farbigkeit          text,
    farben              jsonb,
    chroma_mittel       real,
    hue_streuung        real,
    helligkeit_mittel   real,
    erstellt_am         timestamptz NOT NULL DEFAULT now(),
    farbnamen           jsonb
);


-- ---------------------------------------------------------------------------
-- Generated and audited keywords
--
-- GND columns are part of the supported German-museum reference architecture,
-- but may remain NULL when authority enrichment is disabled.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS museum.enrichment_keywords (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    obj_id       text        NOT NULL,
    cluster      text,
    keyword      text        NOT NULL,

    gnd_name     text,
    gnd_id       text,
    confidence   text,

    status       text,
    llm2         text,
    llm3         text,
    llm4         text,

    audit1       text,
    audit2       text,
    audit3       text,
    audit4       text,
    audit5       text,

    status2      text,
    modell       text,
    erstellt_am  timestamptz NOT NULL DEFAULT now(),
    hinweis      text
);

CREATE INDEX IF NOT EXISTS enr_kw_cluster_idx
    ON museum.enrichment_keywords (cluster);

CREATE INDEX IF NOT EXISTS enr_kw_gnd_idx
    ON museum.enrichment_keywords (gnd_id);

CREATE INDEX IF NOT EXISTS enr_kw_obj_idx
    ON museum.enrichment_keywords (obj_id);

CREATE INDEX IF NOT EXISTS enr_kw_status_idx
    ON museum.enrichment_keywords (status);
